//-----------------------------------------------------------------------------------------------------
//     This code was generated by the Wmi Delphi Code Creator http://theroadtodelphi.wordpress.com
//     Version: 1.9.5.0 
//
//
//
//     LIABILITY DISCLAIMER
//     THIS GENERATED CODE IS DISTRIBUTED "AS IS". NO WARRANTY OF ANY KIND IS EXPRESSED OR IMPLIED.
//     YOU USE IT AT YOUR OWN RISK. THE AUTHOR NOT WILL BE LIABLE FOR DATA LOSS,
//     DAMAGES AND LOSS OF PROFITS OR ANY OTHER KIND OF LOSS WHILE USING OR MISUSING THIS CODE.
//
//
//----------------------------------------------------------------------------------------------------
program GetWMI_Info;

{$APPTYPE CONSOLE}

uses
  SysUtils,
  ActiveX,
  ComObj,
  Variants;
  

    
// Descreve uma instância em tempo como retornado por Win32ClockProvider. Quando 
// uma consulta for enviada para Win32LocalClockProvider, os resultados serão 
// retornados como objetos de Win32_LocalTime com horas correspondentes à 
// consulta. Eles são retornados como parte de  __InstanceModificationEvents

procedure  GetWin32_LocalTimeInfo;
const
  WbemUser            ='';
  WbemPassword        ='';
  WbemComputer        ='localhost';
  wbemFlagForwardOnly = $00000020;
var
  FSWbemLocator : OLEVariant;
  FWMIService   : OLEVariant;
  FWbemObjectSet: OLEVariant;
  FWbemObject   : OLEVariant;
  oEnum         : IEnumvariant;
  iValue        : LongWord;
begin;
  FSWbemLocator := CreateOleObject('WbemScripting.SWbemLocator');
  FWMIService   := FSWbemLocator.ConnectServer(WbemComputer, 'root\CIMV2', WbemUser, WbemPassword);
  FWbemObjectSet:= FWMIService.ExecQuery('SELECT * FROM Win32_LocalTime','WQL',wbemFlagForwardOnly);
  oEnum         := IUnknown(FWbemObjectSet._NewEnum) as IEnumVariant;
  while oEnum.Next(1, FWbemObject, iValue) = 0 do
  begin
    Writeln(Format('Day             %d',[Integer(FWbemObject.Day)]));// Uint32
    Writeln(Format('DayOfWeek       %d',[Integer(FWbemObject.DayOfWeek)]));// Uint32
    Writeln(Format('Hour            %d',[Integer(FWbemObject.Hour)]));// Uint32
    Writeln(Format('Milliseconds    %d',[Integer(FWbemObject.Milliseconds)]));// Uint32
    Writeln(Format('Minute          %d',[Integer(FWbemObject.Minute)]));// Uint32
    Writeln(Format('Month           %d',[Integer(FWbemObject.Month)]));// Uint32
    Writeln(Format('Quarter         %d',[Integer(FWbemObject.Quarter)]));// Uint32
    Writeln(Format('Second          %d',[Integer(FWbemObject.Second)]));// Uint32
    Writeln(Format('WeekInMonth     %d',[Integer(FWbemObject.WeekInMonth)]));// Uint32
    Writeln(Format('Year            %d',[Integer(FWbemObject.Year)]));// Uint32
	    
    Writeln('');
    FWbemObject:=Unassigned;
  end;
end;


begin
 try
    CoInitialize(nil);
    try
      GetWin32_LocalTimeInfo;
    finally
      CoUninitialize;
    end;
 except
    on E:EOleException do
        Writeln(Format('EOleException %s %x', [E.Message,E.ErrorCode])); 
    on E:Exception do
        Writeln(E.Classname, ':', E.Message);
 end;
 Writeln('Press Enter to exit');
 Readln;      
end.